# Config to define all available selections
# Selections contain object- and event-level cuts
# Previously defined selections can be imported with '<<' or '*'
# Any nested collections created by "<<" or '*' operations will be flattened in sidm_processor.py


# basic analysis selections
base: &base
  obj_cuts: &obj_base
    pvs: &pv_base
      - "ndof > 4"
      - "|z| < 24 cm"
      - "|rho| < 0.2 mm"
    ljs: &lj_base
      - "pT > 30 GeV"
      - "|eta| < 2.4"
  evt_cuts: &evt_base
    - "PV filter"
    - "Cosmic veto"
    - ">=2 LJs"

4mu: &4mu
  << : *base
  evt_cuts: &evt_4mu
    - *evt_base
    - "4mu"

2mu2e: &2mu2e
  << : *base
  evt_cuts: &evt_2mu2e
    - *evt_base
    - "2mu2e"

# basic analysis selections with LJ-A dR matching
matchedLj: &matchedLj
  obj_cuts: &obj_matchedLj
    <<: *obj_base
    ljs: 
      - *lj_base
      - "dR(LJ, A) < 0.2"
  evt_cuts: &evt_matchedLj
    - *evt_base
    - ">=2 matched As"

4mu_matchedLj: &4mu_matchedLj
  <<: *matchedLj
  evt_cuts: &evt_4mu_matchedLj
    - *evt_matchedLj
    - "4mu"

2mu2e_matchedLj: &2mu2e_matchedLj
  <<: *matchedLj
  evt_cuts: &evt_2mu2e_matchedLj
    - *evt_matchedLj
    - "2mu2e"
